# Generated by Django 3.0.8 on 2020-07-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.BinaryField(default=b'4d5508baad9da6124bca4fb616f0055ee5f7bb9d', max_length=20),
        ),
    ]
