# Generated by Django 3.0.8 on 2020-07-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200727_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.BinaryField(default=b'2a20dbca7aa31796d10cc225cb8156349483e033', max_length=20),
        ),
    ]
